# Generated by Django 5.2.6 on 2025-09-23 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_test_test_created_at_test_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
