# Generated by Django 5.2.6 on 2025-09-23 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_test_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
