            # Generated by Django 5.2.6 on 2025-09-23 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_test_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
