# Generated by Django 5.2.6 on 2025-09-23 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_test_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shuffle_answers',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='shuffle_questions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='timer_seconds',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
