# Generated by Django 5.2.6 on 2025-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_test_shuffle_answers_test_shuffle_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='shuffle_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='timer_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
