# Generated by Django 5.2 on 2025-09-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_question_audio_question_image_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Текстовый'), ('voice', 'Голосовой'), ('photo', 'Фото')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='answer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='answers/audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый'), ('voice', 'Голосовой'), ('photo', 'Фото')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
