# Generated by Django 5.2 on 2025-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_answer_answer_type_answer_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_format',
            field=models.CharField(choices=[('text', 'Обычный тест'), ('voice', 'Голосовой тест'), ('image', 'Фото тест')], default='text', max_length=10),
        ),
    ]
