# Generated by Django 5.2 on 2025-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_test_test_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/images/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='matching_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='question_format',
            field=models.CharField(choices=[('text_answers', '📸 Вопрос с фото, текстовые ответы'), ('photo_answers', '🖼️ Текст вопрос, ответы с фото'), ('matching', '🎯 Сопоставление фото'), ('find_error', '🔍 Найди ошибку на фото')], default='text_answers', max_length=20),
        ),
    ]
