# Generated by Django 5.2 on 2025-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_answer_image_answer_matching_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_format',
            field=models.CharField(choices=[('text_answers', '📸 Вопрос с фото, текстовые ответы'), ('photo_answers', '🖼️ Текст вопрос, ответы с фото'), ('matching', '🎯 Сопоставление фото'), ('find_error', '🔍 Найди ошибку на фото'), ('math_formula', '🧮 Математическая формула'), ('math_equation', '═ Математическое уравнение')], default='text_answers', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый'), ('voice', 'Голосовой'), ('photo', 'Фото'), ('math', 'Математический тест')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_format',
            field=models.CharField(choices=[('text', 'Обычный тест'), ('voice', 'Голосовой тест'), ('image', 'Фото тест'), ('math', 'Математический тест')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('text', 'Обычный тест'), ('voice', 'Голосовой тест'), ('image', 'Фото тест'), ('math', 'Математический тест')], default='text', max_length=10),
        ),
    ]
