# Generated by Django 5.2 on 2025-10-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_classgroup_testresult_class_group_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='class_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Класс'),
        ),
    ]
