# Generated by Django 5.2 on 2025-10-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_testresult_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='math_expression',
            field=models.TextField(blank=True, null=True, verbose_name='Математическое выражение'),
        ),
    ]
