# Generated by Django 5.2 on 2025-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_question_math_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
