# Generated by Django 5.2 on 2025-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_studentanswer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый'), ('voice', 'Голосовой'), ('photo', 'Фото'), ('math', 'Математический тест'), ('mixed', 'Смешанный тест')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_format',
            field=models.CharField(choices=[('mixed', 'Смешанный тест'), ('text', 'Обычный тест'), ('voice', 'Голосовой тест'), ('image', 'Фото тест'), ('math', 'Математический тест')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('mixed', 'Смешанный тест'), ('text', 'Обычный тест'), ('voice', 'Голосовой тест'), ('image', 'Фото тест'), ('math', 'Математический тест')], default='mixed', max_length=10),
        ),
    ]
