# Generated by Django 5.2 on 2025-10-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_question_question_type_alter_test_test_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='matching_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='quiz.answer'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
