# Generated by Django 5.2 on 2025-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_studentanswer_matching_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='math_expression',
            field=models.TextField(blank=True, null=True, verbose_name='Математическое выражение'),
        ),
    ]
