# Generated by Django 5.2 on 2025-10-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_answer_math_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_solutions/'),
        ),
    ]
