# Generated by Django 5.2 on 2025-10-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_studentanswer_solution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_copying',
            field=models.BooleanField(default=True, verbose_name='Разрешить копирование'),
        ),
        migrations.AddField(
            model_name='test',
            name='copied_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.test', verbose_name='Копирован из'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='test',
            name='visibility',
            field=models.CharField(choices=[('private', 'Приватный'), ('public', 'Публичный'), ('unlisted', 'По ссылке')], default='private', max_length=10, verbose_name='Видимость теста'),
        ),
    ]
