# Generated by Django 5.2 on 2025-10-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_test_allow_copying_test_copied_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='copied_form',
        ),
        migrations.AddField(
            model_name='test',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.test', verbose_name='Скопирован из'),
        ),
    ]
