# Generated by Django 5.2 on 2025-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_school_test_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='school_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='test',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название школы'),
        ),
        migrations.AddField(
            model_name='test',
            name='school_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер школы'),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО учителя'),
        ),
    ]
