# Generated by Django 5.2 on 2025-10-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_test_school_city_test_school_name_test_school_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='visibility',
            field=models.CharField(choices=[('private', 'Приватный'), ('public', 'Публичный'), ('unlisted', 'По ссылке')], default='public', max_length=10, verbose_name='Видимость теста'),
        ),
    ]
