# Generated by Django 5.2 on 2025-10-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_alter_test_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
