# Generated by Django 5.2 on 2025-10-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_alter_test_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='visibility',
            field=models.CharField(choices=[('private', 'Приватный'), ('public', 'Публичный'), ('unlisted', 'По ссылке')], default='private', max_length=10, verbose_name='Видимость теста'),
        ),
    ]
