# Generated by Django 5.2 on 2025-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_alter_test_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
