# Generated by Django 5.2 on 2025-11-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_test_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='require_solution_photo',
            field=models.BooleanField(default=False, verbose_name='Требовать фото решения'),
        ),
    ]
